version: '3.8'

services:
    nginx:
        image: nginx:1.21.1
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www/
        depends_on:
            - php

    php:
        build: ./docker/php
        user: "1000:1000"
        volumes:
            - ./src:/var/www/
        depends_on:
            - mysql
        environment:
            - QUEUE_CONNECTION=database # キューの接続方法を指定
        command: php-fpm
        healthcheck:
            test: ["CMD-SHELL", "if [ -f /var/www/vendor/autoload.php ] && [ -f /var/www/storage/framework/cache/data/.gitignore ]; then exit 0; else echo 'Not ready yet'; exit 1; fi"]
            interval: 10s
            timeout: 5s
            retries: 3

    mysql:
        image: mysql:8.0.26
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: laravel_pass
        command: mysqld --default-authentication-plugin=mysql_native_password
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_USER=laravel_user
            - PMA_PASSWORD=laravel_pass
        depends_on:
            - mysql
        ports:
            - 8080:80

    mailhog:
        image: mailhog/mailhog
        ports:
            - "8025:8025"

    supervisor:
        build: ./docker/supervisor
        volumes:
            - ./src:/var/www/
        depends_on:
            php:
                condition: service_healthy
        command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
